// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type AccountsUser struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	FirstName       string         `db:"first_name" json:"first_name"`
	MiddleName      sql.NullString `db:"middle_name" json:"middle_name"`
	LastName        string         `db:"last_name" json:"last_name"`
	DateOfBirth     sql.NullTime   `db:"date_of_birth" json:"date_of_birth"`
	Gender          sql.NullString `db:"gender" json:"gender"`
	Status          sql.NullString `db:"status" json:"status"`
	Email           string         `db:"email" json:"email"`
	Phone           sql.NullString `db:"phone" json:"phone"`
	IsWhatsappPhone sql.NullBool   `db:"is_whatsapp_phone" json:"is_whatsapp_phone"`
	IsPhoneVerified sql.NullBool   `db:"is_phone_verified" json:"is_phone_verified"`
	IsEmailVerified sql.NullBool   `db:"is_email_verified" json:"is_email_verified"`
	IsNinVerified   sql.NullBool   `db:"is_nin_verified" json:"is_nin_verified"`
	HashType        string         `db:"hash_type" json:"hash_type"`
	HashPassword    string         `db:"hash_password" json:"hash_password"`
	HashPin         string         `db:"hash_pin" json:"hash_pin"`
	HashTableSeq    sql.NullInt16  `db:"hash_table_seq" json:"hash_table_seq"`
	EncryptedNin    sql.NullString `db:"encrypted_nin" json:"encrypted_nin"`
	DeletedAt       sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	CreatedAt       sql.NullTime   `db:"created_at" json:"created_at"`
}
