// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organisations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO "accounts"."organisations" (
    "id", 
    "name", 
    "description", 
    "creator_user_id", 
    "max_co_organisers", 
    "max_active_campaign"
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, creator_user_id, max_co_organisers, max_active_campaign, total_members, total_events, active_events, created_at, total_contributions, permissions
`

type CreateOrganisationParams struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	Name              string      `db:"name" json:"name"`
	Description       pgtype.Text `db:"description" json:"description"`
	CreatorUserID     uuid.UUID   `db:"creator_user_id" json:"creator_user_id"`
	MaxCoOrganisers   int16       `db:"max_co_organisers" json:"max_co_organisers"`
	MaxActiveCampaign int16       `db:"max_active_campaign" json:"max_active_campaign"`
}

// Insert into organisations
func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (AccountsOrganisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatorUserID,
		arg.MaxCoOrganisers,
		arg.MaxActiveCampaign,
	)
	var i AccountsOrganisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUserID,
		&i.MaxCoOrganisers,
		&i.MaxActiveCampaign,
		&i.TotalMembers,
		&i.TotalEvents,
		&i.ActiveEvents,
		&i.CreatedAt,
		&i.TotalContributions,
		&i.Permissions,
	)
	return i, err
}
