// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organisations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO "accounts"."organisations" (
    "id", 
    "name", 
    "description", 
    "creator_user", 
    "max_co_organisers", 
    "max_active_events"
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, creator_user, max_co_organisers, max_active_events, total_members, total_events, active_events, created_at, permissions
`

type CreateOrganisationParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	Name            pgtype.Text `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	CreatorUser     uuid.UUID   `db:"creator_user" json:"creator_user"`
	MaxCoOrganisers pgtype.Int2 `db:"max_co_organisers" json:"max_co_organisers"`
	MaxActiveEvents pgtype.Int2 `db:"max_active_events" json:"max_active_events"`
}

// Insert into organisations
func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (AccountsOrganisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatorUser,
		arg.MaxCoOrganisers,
		arg.MaxActiveEvents,
	)
	var i AccountsOrganisation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatorUser,
		&i.MaxCoOrganisers,
		&i.MaxActiveEvents,
		&i.TotalMembers,
		&i.TotalEvents,
		&i.ActiveEvents,
		&i.CreatedAt,
		&i.Permissions,
	)
	return i, err
}
