// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO accounts.users (
    "id",
    "first_name", 
    "middle_name", 
    "last_name", 
    "date_of_birth", 
    "gender",
    "email", 
    "phone",
    "is_whatsapp_phone", 
    "status",
    "hash_type", 
    "hash_password", 
    "hash_pin",
    "hash_table_seq"
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14
)
RETURNING id, first_name, middle_name, last_name, date_of_birth, gender, status, email, phone, is_whatsapp_phone, is_phone_verified, is_email_verified, is_nin_verified, hash_type, hash_password, hash_pin, hash_table_seq, encrypted_nin, deleted_at, created_at
`

type CreateUserParams struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	FirstName       string         `db:"first_name" json:"first_name"`
	MiddleName      sql.NullString `db:"middle_name" json:"middle_name"`
	LastName        string         `db:"last_name" json:"last_name"`
	DateOfBirth     sql.NullTime   `db:"date_of_birth" json:"date_of_birth"`
	Gender          sql.NullString `db:"gender" json:"gender"`
	Email           string         `db:"email" json:"email"`
	Phone           sql.NullString `db:"phone" json:"phone"`
	IsWhatsappPhone sql.NullBool   `db:"is_whatsapp_phone" json:"is_whatsapp_phone"`
	Status          sql.NullString `db:"status" json:"status"`
	HashType        string         `db:"hash_type" json:"hash_type"`
	HashPassword    string         `db:"hash_password" json:"hash_password"`
	HashPin         string         `db:"hash_pin" json:"hash_pin"`
	HashTableSeq    sql.NullInt16  `db:"hash_table_seq" json:"hash_table_seq"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AccountsUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Email,
		arg.Phone,
		arg.IsWhatsappPhone,
		arg.Status,
		arg.HashType,
		arg.HashPassword,
		arg.HashPin,
		arg.HashTableSeq,
	)
	var i AccountsUser
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.Email,
		&i.Phone,
		&i.IsWhatsappPhone,
		&i.IsPhoneVerified,
		&i.IsEmailVerified,
		&i.IsNinVerified,
		&i.HashType,
		&i.HashPassword,
		&i.HashPin,
		&i.HashTableSeq,
		&i.EncryptedNin,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
